# Generated by Django 3.2.7 on 2021-12-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='Внешний ID пользователя')),
                ('name', models.TextField(verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('wishlist', models.CharField(max_length=256, verbose_name='Интересы')),
                ('message_for_Santa', models.TextField(verbose_name='Письмо Санте')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price_limit_status', models.BooleanField(default=False, verbose_name='Нравится')),
                ('price_limit', models.CharField(max_length=256)),
                ('registration_date', models.DateTimeField()),
                ('gift_dispatch_date', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='santa_bot.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
