# Generated by Django 3.2.7 on 2021-12-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='profile',
        ),
        migrations.AddField(
            model_name='game',
            name='creator_chat_id',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='game',
            name='gift_dispatch_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='price_limit',
            field=models.CharField(default='Золотая карта', max_length=256),
        ),
        migrations.AlterField(
            model_name='game',
            name='price_limit_status',
            field=models.BooleanField(default=False, verbose_name='Есть лимит'),
        ),
        migrations.AlterField(
            model_name='game',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
