# Generated by Django 3.2.7 on 2021-12-17 13:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('santa_bot', '0002_auto_20211217_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='participants',
            field=jsonfield.fields.JSONField(default=False),
        ),
    ]
