# Generated by Django 3.2.7 on 2021-12-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_bot', '0002_auto_20211216_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gift_dispatch_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
