# Generated by Django 3.2.7 on 2021-12-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_bot', '0002_auto_20211218_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raffle', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Провести жеребьевку',
            },
        ),
    ]
