# Generated by Django 3.2.7 on 2021-12-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_bot', '0003_game_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_hash',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='game',
            name='price_limit_status',
            field=models.BooleanField(default=False, verbose_name='Безлимит'),
        ),
    ]
