# Generated by Django 3.2.7 on 2021-12-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_bot', '0003_auto_20211216_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creator_chat_id',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
