# Generated by Django 3.2.7 on 2021-12-18 09:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('santa_bot', '0004_auto_20211218_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='participants',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
